# Audio settings
TARGET_SAMPLE_RATE = 16000
MONO = True

# RoI detection settings
FRAME_DURATION = 0.025
HOP_DURATION = 0.010

ROI_THRESHOLD_FACTOR = 2.0
ROI_MIN_DURATION = 0.30
ROI_MERGE_GAP = 0.50
ROI_PADDING = 0.25

# Noise filtering
HIGHPASS_CUTOFF = 1000

# BirdNET classification
BIRDNET_MIN_CONFIDENCE = 0.25
BIRDNET_TOP_K = 5
BIRDNET_MIN_DURATION = 3.0