"""create initial birdcall schema

Revision ID: c5952480b87a
Revises: 
Create Date: 2026-07-30 01:44:54.677843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5952480b87a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_devices_ck_devices_valid_latitude')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_devices_ck_devices_valid_longitude')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_code', name=op.f('uq_devices_device_code'))
    )
    op.create_index('ix_devices_is_active', 'devices', ['is_active'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='processing_status'), server_default='pending', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.CheckConstraint('channel_count > 0', name=op.f('ck_recordings_ck_recordings_positive_channel_count')),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_recordings_ck_recordings_positive_duration')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_recordings_ck_recordings_valid_latitude')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_recordings_ck_recordings_valid_longitude')),
    sa.CheckConstraint('sample_rate > 0', name=op.f('ck_recordings_ck_recordings_positive_sample_rate')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_recordings_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('device_id', 'checksum_sha256', name='uq_recordings_device_checksum'),
    sa.UniqueConstraint('file_path', name=op.f('uq_recordings_file_path')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_recordings_stored_filename'))
    )
    op.create_index('ix_recordings_device_recorded_at', 'recordings', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_recordings_processing_status', 'recordings', ['processing_status'], unique=False)
    op.create_index('ix_recordings_recorded_at', 'recordings', ['recorded_at'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('scientific_name', sa.String(length=180), nullable=False),
    sa.Column('common_name', sa.String(length=180), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=False),
    sa.Column('end_time_seconds', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_detections_ck_detections_valid_confidence')),
    sa.CheckConstraint('end_time_seconds > start_time_seconds', name=op.f('ck_detections_ck_detections_valid_interval')),
    sa.CheckConstraint('start_time_seconds >= 0', name=op.f('ck_detections_ck_detections_nonnegative_start')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_detections_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detections')),
    sa.UniqueConstraint('recording_id', 'scientific_name', 'start_time_seconds', 'end_time_seconds', 'model_name', 'model_version', name='uq_detections_recording_species_interval_model')
    )
    op.create_index('ix_detections_common_name', 'detections', ['common_name'], unique=False)
    op.create_index('ix_detections_confidence', 'detections', ['confidence'], unique=False)
    op.create_index('ix_detections_created_at', 'detections', ['created_at'], unique=False)
    op.create_index('ix_detections_recording_id', 'detections', ['recording_id'], unique=False)
    op.create_index('ix_detections_scientific_name', 'detections', ['scientific_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_scientific_name', table_name='detections')
    op.drop_index('ix_detections_recording_id', table_name='detections')
    op.drop_index('ix_detections_created_at', table_name='detections')
    op.drop_index('ix_detections_confidence', table_name='detections')
    op.drop_index('ix_detections_common_name', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_recordings_recorded_at', table_name='recordings')
    op.drop_index('ix_recordings_processing_status', table_name='recordings')
    op.drop_index('ix_recordings_device_recorded_at', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index('ix_devices_is_active', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
