from __future__ import annotations

import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.orm import Mapped, mapped_column, relationship

from core.db import Base

if TYPE_CHECKING:
    from models.detection import Detection
    from models.device import Device


class ProcessingStatus(str, enum.Enum):
    """Current BirdNET processing state of an ROI snippet."""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class Recording(Base):
    """
    One audio ROI snippet uploaded by an edge device.

    A Recording does not represent the complete continuous capture.
    Multiple Recording rows may belong to the same capture session.
    """

    __tablename__ = "recordings"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    device_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "devices.id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # Identifier generated by the ESP32 for retry-safe uploads.
    #
    # Repeating an upload with the same device_id and client_upload_id
    # must return the existing recording rather than creating a new one.
    client_upload_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    # Identifier shared by all ROI snippets extracted from the same
    # continuous capture period.
    capture_session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    # Sequence number of this ROI within its capture session.
    # Zero-based numbering is recommended for the ESP32 implementation.
    snippet_sequence: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    original_filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    stored_filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
    )

    # Internal backend path. This must not be exposed through public API
    # response schemas.
    file_path: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        unique=True,
    )

    checksum_sha256: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
    )

    file_size_bytes: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
    )

    # Absolute timestamp at which the original continuous capture began.
    capture_started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Absolute timestamp at which this ROI snippet began.
    #
    # For ESP32 uploads:
    # recorded_at = capture_started_at + roi_start_seconds
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # Position of this ROI within the original continuous capture.
    roi_start_seconds: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    roi_end_seconds: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    processing_started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    processed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Audio properties are calculated by the backend from the uploaded
    # WAV file. Values supplied by the ESP32 are not trusted directly.
    duration_seconds: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    sample_rate: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    channel_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    latitude: Mapped[Decimal | None] = mapped_column(
        Numeric(9, 6),
        nullable=True,
    )

    longitude: Mapped[Decimal | None] = mapped_column(
        Numeric(9, 6),
        nullable=True,
    )

    # Version of the edge-side ROI processing algorithm.
    #
    # Example:
    # "roi-pipeline-1.0.0"
    edge_processing_version: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    # Flexible metadata describing the ESP32 preprocessing parameters.
    #
    # Example:
    # {
    #     "firmware_version": "0.1.0",
    #     "normalization": {"enabled": true},
    #     "energy_detection": {
    #         "window_samples": 1024,
    #         "threshold": 0.18
    #     },
    #     "roi_margin_seconds": 0.5,
    #     "high_pass_filter": {
    #         "enabled": true,
    #         "cutoff_hz": 1000,
    #         "order": 4
    #     }
    # }
    edge_processing_metadata: Mapped[dict[str, Any]] = mapped_column(
        MutableDict.as_mutable(JSONB),
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
    )

    processing_status: Mapped[ProcessingStatus] = mapped_column(
        Enum(
            ProcessingStatus,
            name="processing_status",
            values_callable=lambda enum_class: [
                member.value for member in enum_class
            ],
        ),
        nullable=False,
        default=ProcessingStatus.PENDING,
        server_default=ProcessingStatus.PENDING.value,
    )

    processing_error: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    device: Mapped["Device"] = relationship(
        back_populates="recordings",
    )

    detections: Mapped[list["Detection"]] = relationship(
        back_populates="recording",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    __table_args__ = (
        # Content-level duplicate protection.
        UniqueConstraint(
            "device_id",
            "checksum_sha256",
            name="uq_recordings_device_checksum",
        ),

        # Network retry/idempotency protection.
        #
        # PostgreSQL permits multiple NULL values, which allows legacy
        # records to remain valid.
        UniqueConstraint(
            "device_id",
            "client_upload_id",
            name="uq_recordings_device_client_upload",
        ),

        CheckConstraint(
            "file_size_bytes > 0",
            name="ck_recordings_positive_file_size",
        ),
        CheckConstraint(
            "duration_seconds > 0",
            name="ck_recordings_positive_duration",
        ),
        CheckConstraint(
            "sample_rate > 0",
            name="ck_recordings_positive_sample_rate",
        ),
        CheckConstraint(
            "channel_count > 0",
            name="ck_recordings_positive_channel_count",
        ),
        CheckConstraint(
            (
                "snippet_sequence IS NULL "
                "OR snippet_sequence >= 0"
            ),
            name="ck_recordings_nonnegative_snippet_sequence",
        ),

        # ROI start and end must either both be absent or form a valid
        # positive interval.
        CheckConstraint(
            (
                "("
                "roi_start_seconds IS NULL "
                "AND roi_end_seconds IS NULL"
                ") "
                "OR "
                "("
                "roi_start_seconds >= 0 "
                "AND roi_end_seconds > roi_start_seconds"
                ")"
            ),
            name="ck_recordings_valid_roi_interval",
        ),
        CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name="ck_recordings_valid_latitude",
        ),
        CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name="ck_recordings_valid_longitude",
        ),
        Index(
            "ix_recordings_device_recorded_at",
            "device_id",
            "recorded_at",
        ),
        Index(
            "ix_recordings_device_capture_session",
            "device_id",
            "capture_session_id",
        ),
        Index(
            "ix_recordings_capture_session_sequence",
            "capture_session_id",
            "snippet_sequence",
        ),
        Index(
            "ix_recordings_processing_status",
            "processing_status",
        ),
        Index(
            "ix_recordings_recorded_at",
            "recorded_at",
        ),
    )