"""add ROI recording metadata

Revision ID: 5e822744c7c5
Revises: 40520d352285
Create Date: 2026-07-30 03:21:33.290012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e822744c7c5'
down_revision: Union[str, Sequence[str], None] = '40520d352285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('client_upload_id', sa.UUID(), nullable=True))
    op.add_column('recordings', sa.Column('capture_session_id', sa.UUID(), nullable=True))
    op.add_column('recordings', sa.Column('snippet_sequence', sa.Integer(), nullable=True))
    op.add_column('recordings', sa.Column('capture_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recordings', sa.Column('roi_start_seconds', sa.Float(), nullable=True))
    op.add_column('recordings', sa.Column('roi_end_seconds', sa.Float(), nullable=True))
    op.add_column('recordings', sa.Column('edge_processing_version', sa.String(length=100), nullable=True))
    op.add_column('recordings', sa.Column('edge_processing_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_index('ix_recordings_capture_session_sequence', 'recordings', ['capture_session_id', 'snippet_sequence'], unique=False)
    op.create_index('ix_recordings_device_capture_session', 'recordings', ['device_id', 'capture_session_id'], unique=False)
    op.create_unique_constraint('uq_recordings_device_client_upload', 'recordings', ['device_id', 'client_upload_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recordings_device_client_upload', 'recordings', type_='unique')
    op.drop_index('ix_recordings_device_capture_session', table_name='recordings')
    op.drop_index('ix_recordings_capture_session_sequence', table_name='recordings')
    op.drop_column('recordings', 'edge_processing_metadata')
    op.drop_column('recordings', 'edge_processing_version')
    op.drop_column('recordings', 'roi_end_seconds')
    op.drop_column('recordings', 'roi_start_seconds')
    op.drop_column('recordings', 'capture_started_at')
    op.drop_column('recordings', 'snippet_sequence')
    op.drop_column('recordings', 'capture_session_id')
    op.drop_column('recordings', 'client_upload_id')
    # ### end Alembic commands ###
