"""scope recording checksum uniqueness to capture session

Revision ID: 6d6e486a2134
Revises: bd704f8f5def
Create Date: 2026-08-14 03:06:07.843905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6e486a2134'
down_revision: Union[str, Sequence[str], None] = 'bd704f8f5def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_recordings_device_checksum'), 'recordings', type_='unique')
    op.create_unique_constraint('uq_recordings_device_session_checksum', 'recordings', ['device_id', 'capture_session_id', 'checksum_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recordings_device_session_checksum', 'recordings', type_='unique')
    op.create_unique_constraint(op.f('uq_recordings_device_checksum'), 'recordings', ['device_id', 'checksum_sha256'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
