"""align schema with simplified backend

Revision ID: bd704f8f5def
Revises: 5e822744c7c5
Create Date: 2026-08-14 01:02:43.491980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd704f8f5def'
down_revision: Union[str, Sequence[str], None] = '5e822744c7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_detections_ck_detections_nonnegative_start'), 'detections', type_='check')
    op.drop_constraint(op.f('ck_detections_ck_detections_valid_confidence'), 'detections', type_='check')
    op.drop_constraint(op.f('ck_detections_ck_detections_valid_interval'), 'detections', type_='check')
    op.create_check_constraint('ck_detections_nonnegative_start', 'detections', 'start_time_seconds >= 0')
    op.create_check_constraint('ck_detections_valid_confidence', 'detections', 'confidence BETWEEN 0 AND 1')
    op.create_check_constraint('ck_detections_valid_interval', 'detections', 'end_time_seconds > start_time_seconds')
    op.drop_constraint(op.f('ck_devices_ck_devices_valid_latitude'), 'devices', type_='check')
    op.drop_constraint(op.f('ck_devices_ck_devices_valid_longitude'), 'devices', type_='check')
    op.create_check_constraint('ck_devices_valid_latitude', 'devices', 'latitude IS NULL OR latitude BETWEEN -90 AND 90')
    op.create_check_constraint('ck_devices_valid_longitude', 'devices', 'longitude IS NULL OR longitude BETWEEN -180 AND 180')
    op.drop_constraint(op.f('ck_recordings_ck_recordings_positive_channel_count'), 'recordings', type_='check')
    op.drop_constraint(op.f('ck_recordings_ck_recordings_positive_duration'), 'recordings', type_='check')
    op.drop_constraint(op.f('ck_recordings_ck_recordings_positive_sample_rate'), 'recordings', type_='check')
    op.drop_constraint(op.f('ck_recordings_ck_recordings_valid_latitude'), 'recordings', type_='check')
    op.drop_constraint(op.f('ck_recordings_ck_recordings_valid_longitude'), 'recordings', type_='check')
    op.create_check_constraint('ck_recordings_nonnegative_snippet_sequence', 'recordings', 'snippet_sequence IS NULL OR snippet_sequence >= 0')
    op.create_check_constraint('ck_recordings_positive_channel_count', 'recordings', 'channel_count > 0')
    op.create_check_constraint('ck_recordings_positive_duration', 'recordings', 'duration_seconds > 0')
    op.create_check_constraint('ck_recordings_positive_file_size', 'recordings', 'file_size_bytes > 0')
    op.create_check_constraint('ck_recordings_positive_sample_rate', 'recordings', 'sample_rate > 0')
    op.create_check_constraint('ck_recordings_valid_latitude', 'recordings', 'latitude IS NULL OR latitude BETWEEN -90 AND 90')
    op.create_check_constraint('ck_recordings_valid_longitude', 'recordings', 'longitude IS NULL OR longitude BETWEEN -180 AND 180')
    op.create_check_constraint('ck_recordings_valid_roi_interval', 'recordings', '(roi_start_seconds IS NULL AND roi_end_seconds IS NULL) OR (roi_start_seconds >= 0 AND roi_end_seconds > roi_start_seconds)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_recordings_valid_roi_interval', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_valid_longitude', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_valid_latitude', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_positive_sample_rate', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_positive_file_size', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_positive_duration', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_positive_channel_count', 'recordings', type_='check')
    op.drop_constraint('ck_recordings_nonnegative_snippet_sequence', 'recordings', type_='check')
    op.create_check_constraint(op.f('ck_recordings_ck_recordings_valid_longitude'), 'recordings', "longitude IS NULL OR longitude >= '-180'::integer::numeric AND longitude <= 180::numeric")
    op.create_check_constraint(op.f('ck_recordings_ck_recordings_valid_latitude'), 'recordings', "latitude IS NULL OR latitude >= '-90'::integer::numeric AND latitude <= 90::numeric")
    op.create_check_constraint(op.f('ck_recordings_ck_recordings_positive_sample_rate'), 'recordings', 'sample_rate > 0')
    op.create_check_constraint(op.f('ck_recordings_ck_recordings_positive_duration'), 'recordings', 'duration_seconds > 0::double precision')
    op.create_check_constraint(op.f('ck_recordings_ck_recordings_positive_channel_count'), 'recordings', 'channel_count > 0')
    op.drop_constraint('ck_devices_valid_longitude', 'devices', type_='check')
    op.drop_constraint('ck_devices_valid_latitude', 'devices', type_='check')
    op.create_check_constraint(op.f('ck_devices_ck_devices_valid_longitude'), 'devices', "longitude IS NULL OR longitude >= '-180'::integer::numeric AND longitude <= 180::numeric")
    op.create_check_constraint(op.f('ck_devices_ck_devices_valid_latitude'), 'devices', "latitude IS NULL OR latitude >= '-90'::integer::numeric AND latitude <= 90::numeric")
    op.drop_constraint('ck_detections_valid_interval', 'detections', type_='check')
    op.drop_constraint('ck_detections_valid_confidence', 'detections', type_='check')
    op.drop_constraint('ck_detections_nonnegative_start', 'detections', type_='check')
    op.create_check_constraint(op.f('ck_detections_ck_detections_valid_interval'), 'detections', 'end_time_seconds > start_time_seconds')
    op.create_check_constraint(op.f('ck_detections_ck_detections_valid_confidence'), 'detections', 'confidence >= 0::double precision AND confidence <= 1::double precision')
    op.create_check_constraint(op.f('ck_detections_ck_detections_nonnegative_start'), 'detections', 'start_time_seconds >= 0::double precision')
    # ### end Alembic commands ###
