import json
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Annotated, Any

from fastapi import (
    APIRouter,
    BackgroundTasks,
    File,
    Form,
    Query,
    Response,
    UploadFile,
    status,
)

from api.dependencies import (
    DatabaseSession,
    PageNumber,
    PageSize,
)
from core.config import settings
from core.exceptions import (
    InvalidUploadMetadataError,
)
from models.recording import ProcessingStatus
from schemas.common import (
    ErrorResponse,
    PaginatedResponse,
)
from schemas.detection import (
    DetectionResponse,
)
from schemas.recording import (
    RecordingResponse,
    RecordingSummaryResponse,
    RecordingUploadMetadata,
    RecordingUploadResponse,
)
from services.detection_service import (
    DetectionService,
)
from services.recording_service import (
    RecordingService,
)
from tasks.recording_tasks import (
    process_recording_background,
)


router = APIRouter(
    prefix="/api/v1/recordings",
    tags=["Recordings"],
)


def parse_edge_processing_metadata(
    raw_metadata: str,
) -> dict[str, Any]:
    """
    Parse and validate the edge-processing metadata supplied as
    a multipart form field.
    """

    metadata_size = len(
        raw_metadata.encode("utf-8")
    )

    if (
        metadata_size
        > settings.max_edge_metadata_size_bytes
    ):
        raise InvalidUploadMetadataError(
            "edge_processing_metadata exceeds the "
            f"{settings.max_edge_metadata_size_bytes}-byte "
            "limit."
        )

    try:
        parsed_metadata = json.loads(
            raw_metadata
        )

    except json.JSONDecodeError as exception:
        raise InvalidUploadMetadataError(
            "edge_processing_metadata must contain "
            "valid JSON."
        ) from exception

    if not isinstance(
        parsed_metadata,
        dict,
    ):
        raise InvalidUploadMetadataError(
            "edge_processing_metadata must be a "
            "JSON object."
        )

    return parsed_metadata


@router.post(
    "",
    response_model=RecordingUploadResponse,
    status_code=status.HTTP_201_CREATED,
    responses={
        200: {
            "model": RecordingUploadResponse,
            "description": (
                "Idempotent retry. The existing recording "
                "is returned."
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": "Device not found.",
        },
        409: {
            "model": ErrorResponse,
            "description": (
                "Inactive device, duplicate content or reused "
                "upload identifier."
            ),
        },
        413: {
            "model": ErrorResponse,
            "description": "Uploaded file is too large.",
        },
        422: {
            "model": ErrorResponse,
            "description": (
                "Invalid audio file or ROI metadata."
            ),
        },
    },
)
async def upload_recording(
    background_tasks: BackgroundTasks,
    response: Response,
    session: DatabaseSession,
    device_id: Annotated[
        uuid.UUID,
        Form(
            description=(
                "Database UUID of the device uploading "
                "the ROI snippet."
            ),
        ),
    ],
    client_upload_id: Annotated[
        uuid.UUID,
        Form(
            description=(
                "UUID generated by the ESP32 for retry-safe "
                "upload handling."
            ),
        ),
    ],
    capture_session_id: Annotated[
        uuid.UUID,
        Form(
            description=(
                "UUID shared by all snippets from one "
                "continuous capture session."
            ),
        ),
    ],
    snippet_sequence: Annotated[
        int,
        Form(
            ge=0,
            description=(
                "Zero-based ROI sequence number within the "
                "capture session."
            ),
        ),
    ],
    capture_started_at: Annotated[
        datetime,
        Form(
            description=(
                "Timezone-aware start timestamp of the "
                "continuous capture session."
            ),
        ),
    ],
    roi_start_seconds: Annotated[
        float,
        Form(
            ge=0,
            description=(
                "Start of this ROI relative to the continuous "
                "capture session."
            ),
        ),
    ],
    roi_end_seconds: Annotated[
        float,
        Form(
            gt=0,
            description=(
                "End of this ROI relative to the continuous "
                "capture session."
            ),
        ),
    ],
    edge_processing_version: Annotated[
        str,
        Form(
            min_length=1,
            max_length=100,
            description=(
                "Version of the ESP32 ROI-processing pipeline."
            ),
        ),
    ],
    edge_processing_metadata: Annotated[
        str,
        Form(
            description=(
                "JSON object describing normalization, energy "
                "detection, filtering and firmware parameters."
            ),
        ),
    ],
    audio_file: Annotated[
        UploadFile,
        File(
            description=(
                "Preprocessed mono PCM WAV ROI snippet."
            ),
        ),
    ],
    latitude: Annotated[
        Decimal | None,
        Form(
            ge=-90,
            le=90,
            description=(
                "Optional latitude captured by the device."
            ),
        ),
    ] = None,
    longitude: Annotated[
        Decimal | None,
        Form(
            ge=-180,
            le=180,
            description=(
                "Optional longitude captured by the device."
            ),
        ),
    ] = None,
) -> RecordingUploadResponse:
    """
    Upload one processed ROI snippet.

    Newly created recordings are queued for BirdNET processing.
    Idempotent retries return the existing recording without
    triggering duplicate processing.
    """

    parsed_edge_metadata = (
        parse_edge_processing_metadata(
            edge_processing_metadata
        )
    )

    upload_metadata = RecordingUploadMetadata(
        client_upload_id=client_upload_id,
        capture_session_id=capture_session_id,
        snippet_sequence=snippet_sequence,
        capture_started_at=capture_started_at,
        roi_start_seconds=roi_start_seconds,
        roi_end_seconds=roi_end_seconds,
        edge_processing_version=(
            edge_processing_version
        ),
        edge_processing_metadata=(
            parsed_edge_metadata
        ),
        latitude=latitude,
        longitude=longitude,
    )

    service = RecordingService(
        session
    )

    result = await service.upload_recording(
        device_id=device_id,
        upload=audio_file,
        metadata=upload_metadata,
    )

    if result.created:
        response.status_code = (
            status.HTTP_201_CREATED
        )

        message = (
            "ROI recording uploaded successfully."
        )

        background_tasks.add_task(
            process_recording_background,
            result.recording.id,
        )

    else:
        response.status_code = (
            status.HTTP_200_OK
        )

        message = (
            "The upload was already completed. "
            "The existing recording has been returned."
        )

    return RecordingUploadResponse(
        message=message,
        created=result.created,
        recording=RecordingResponse.model_validate(
            result.recording
        ),
    )


@router.get(
    "",
    response_model=PaginatedResponse[
        RecordingSummaryResponse
    ],
)
async def list_recordings(
    session: DatabaseSession,
    page: PageNumber = 1,
    page_size: PageSize = 20,
    device_id: Annotated[
        uuid.UUID | None,
        Query(
            description=(
                "Return recordings from a specific device."
            ),
        ),
    ] = None,
    capture_session_id: Annotated[
        uuid.UUID | None,
        Query(
            description=(
                "Return ROI snippets from a capture session."
            ),
        ),
    ] = None,
    processing_status: Annotated[
        ProcessingStatus | None,
        Query(
            description=(
                "Return recordings with a particular "
                "BirdNET processing status."
            ),
        ),
    ] = None,
) -> PaginatedResponse[
    RecordingSummaryResponse
]:
    """
    Return a paginated list of uploaded ROI recordings.
    """

    service = RecordingService(
        session
    )

    return await service.list_recordings(
        page=page,
        page_size=page_size,
        device_id=device_id,
        capture_session_id=capture_session_id,
        processing_status=processing_status,
    )


@router.get(
    "/{recording_id}/detections",
    response_model=list[DetectionResponse],
    responses={
        404: {
            "model": ErrorResponse,
            "description": "Recording not found.",
        },
    },
)
async def get_recording_detections(
    recording_id: uuid.UUID,
    session: DatabaseSession,
) -> list[DetectionResponse]:
    """
    Return every BirdNET detection belonging to one recording.

    An empty list is returned when the recording exists but no
    detections passed the configured confidence threshold.
    """

    service = DetectionService(
        session
    )

    return await service.get_recording_detections(
        recording_id
    )


@router.get(
    "/{recording_id}",
    response_model=RecordingResponse,
    responses={
        404: {
            "model": ErrorResponse,
            "description": "Recording not found.",
        },
    },
)
async def get_recording(
    recording_id: uuid.UUID,
    session: DatabaseSession,
) -> RecordingResponse:
    """
    Return one recording by its UUID.
    """

    service = RecordingService(
        session
    )

    recording = await service.get_recording(
        recording_id
    )

    return RecordingResponse.model_validate(
        recording
    )


@router.delete(
    "/{recording_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    responses={
        404: {
            "model": ErrorResponse,
            "description": "Recording not found.",
        },
    },
)
async def delete_recording(
    recording_id: uuid.UUID,
    session: DatabaseSession,
) -> Response:
    """
    Delete one recording and its associated detections.
    """

    service = RecordingService(
        session
    )

    await service.delete_recording(
        recording_id
    )

    return Response(
        status_code=status.HTTP_204_NO_CONTENT,
    )

